# Generated by Django 4.1.4 on 2022-12-15 19:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.PositiveSmallIntegerField(choices=[(1, 'Informational campaign'), (2, 'Politician reachout'), (3, 'Neighbood event')], default=1)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('due_date', models.DateField(default=datetime.date(2023, 3, 15))),
                ('completed_on', models.DateField(null=True)),
                ('completion_note', models.TextField(null=True)),
                ('url', models.URLField(blank=True)),
                ('contact_person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='campaigns.contactperson')),
            ],
        ),
    ]
