# Generated by Django 4.1.4 on 2022-12-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='completed_on',
        ),
        migrations.AddField(
            model_name='campaign',
            name='ready_for_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
