# Generated by Django 4.1.4 on 2022-12-18 04:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_cover_image_alter_campaign_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Updates',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='campaigns.campaignupdates'),
        ),
    ]
