# Generated by Django 4.1.4 on 2022-12-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignupdates_alter_campaign_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='Updates',
        ),
        migrations.AddField(
            model_name='campaign',
            name='updates',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaignupdates'),
        ),
    ]
