# Generated by Django 4.1.4 on 2022-12-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaign_updates_campaign_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignUpdates',
            new_name='CampaignUpdate',
        ),
    ]
