# Generated by Django 4.1.4 on 2022-12-19 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_rename_campaignupdates_campaignupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='updates',
            new_name='update',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 3, 19)),
        ),
    ]
