# Generated by Django 4.1.4 on 2022-12-19 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_rename_updates_campaign_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='update',
        ),
        migrations.AddField(
            model_name='campaignupdate',
            name='campaign',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign'),
        ),
    ]
