# Generated by Django 4.1.4 on 2022-12-20 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_remove_campaign_update_campaignupdate_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 3, 20)),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('handle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('url', models.URLField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
