# Generated by Django 4.1.4 on 2022-12-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_campaign_due_date_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'Letter'), (3, 'Tweet'), (3, 'Instagram'), (0, 'Other')], default=1),
        ),
    ]
