# Generated by Django 4.1.4 on 2022-12-27 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='actionfiles/'),
        ),
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'Letter'), (3, 'Tweet'), (4, 'Instagram'), (5, 'Petitions'), (0, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 3, 27)),
        ),
    ]
